services:
  - type: web
    name: pokemon-orchestrator
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_ALLOWED_USERS
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: AI_MODEL
        value: google/gemini-2.0-flash-exp:free
      - key: CONTENT_BOT_URL
        sync: false
      - key: COMMUNITY_BOT_URL
        sync: false
      - key: TOYTSUKY_URL
        sync: false
      - key: TIMEZONE
        value: America/Bogota
      - key: PLAN_HOUR
        value: "1"
      - key: ANALYTICS_HOUR
        value: "23"
      - key: CLOUDINARY_CLOUD_NAME
        value: pr45otub
      - key: CLOUDINARY_API_KEY
        value: "185278746692157"
      - key: CLOUDINARY_API_SECRET
        value: z18bJOcV1ZCA0cREdJPdbBFTCHE
